# 지출/소득 계산을 계산할 일자
target_month: 2025-12-01

# 파일 경로
input_path: data/input
output_path: data/output
temp_path: data/temp
prepro_path: data/prepro

# 입력 파일 관련
input_file_names: # 소득/지출이 포함된 뱅크샐러드 데이터
  - 권석현_2025-01-03~2026-01-03.xlsx
  - 신지희_2024-12-14~2025-12-14.xlsx
sheet_name: 가계부 내역 # 뱅크샐러드 데이터내 가게부 내역 시트 이름
asset_file_name: asset.xlsx # 하드코딩되는 자산 데이터
column_names: # 가게부 내역 시트에서 참조할 컬럼
  - 날짜
  - 시간
  - 타입
  - 대분류
  - 소분류
  - 내용
  - 금액
  - 화폐
  - 결제수단
  - 메모
payment_methods: # 지출 계산시 참조되는 결제 수단
  - Discount Plan
  - 스페셜_전자랜드(모바일)
income_sources: # 소득 계산시 참조되는 출처
  - 급여
  - 상여금
  - 사업수입
  - 부동산
exclude_large_cat: # 계산할 때 제외되는 대분류 조건
  - 미분류

# 출력 파일
output_file_name: output_latest.xlsx # 최종 산출물
temp_file_name: temp_{date}.csv
prepro_file_name: prepro_{date}.csv

# 계좌번호
