target_month: 2025-11-01
input_path: data/input
output_path: data/output
temp_path: data/temp
prepro_path: data/prepro
input_file_names:
  - 권석현_2024-11-28~2025-11-28.xlsx
  - 신지희_2024-11-28~2025-11-28.xlsx
output_file_name: output_latest.xlsx
save_temp_file: True
temp_file_name: temp_{date}.csv
prepro_file_name: prepro_{date}.csv
sheet_name: 가계부 내역
column_names:
  - 날짜
  - 시간
  - 타입
  - 대분류
  - 소분류
  - 내용
  - 금액
  - 화폐
  - 결제수단
  - 메모
payment_methods:
  - Discount Plan
income_sources:
  - 급여
  - 상여금
  - 사업수입
  - 부동산
exclude_large_cat:
  - 미분류